{{- with .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.serviceAccount.name }}
  labels:
    app: webapp-color
    {{- range $.Values.serviceAccount.labels }}
    tier:  {{ . }}
    {{- end }}
{{- end }}
